# Color can be used as hax, 256-color, by name (red, green, ...)

format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$container\
$shell\
$character"""

# Enable the blank line at the start of the prompt
add_newline = true

# Makes prompt a single line
[line_break]
disabled = true

[username]
style_root = 'bold red'
style_user = 'bold yellow' # Hex can be used
format = '[$user]($style) in '
show_always = true
disabled = true

[directory]
truncation_length = 2
truncate_to_repo = false
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'bold italic cyan'
disabled = false
home_symbol = '~'
read_only = " 󰌾"
read_only_style = 'red'
truncation_symbol = '…/'

[character]
format = '$symbol '
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
disabled = false

[cmd_duration]
min_time = 10_000
show_milliseconds = false
format = 'took [$duration]($style) '
style = 'bold yellow'
disabled = false

[git_branch]
symbol = " "

[git_status]
deleted = ''
modified = '  '
